# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        pip install -r dev-requires.txt
    - name: Test with pytest
      run: |
        pytest
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length 100 --extend-ignore E203 --show-source --statistics
    - name: Check formatting with black
      run: |
        black . --line-length 100 --diff --check
